#tomcat端口
server:
  port: 8012
  context-path: /eddy
spring:
  application:
    name: yw2
eureka:
  instance:
    hostname: localhost
  client: #not a client,don't register with yourself
    registerWithEureka: true
    fetchRegistry: false